#  API Testing for Product Management

# GET /api/v1/products/

GET http://127.0.0.1:8000/api/v1/products HTTP/1.1

###
# POST /api/v1/products/

POST http://127.0.0.1:8000/api/v1/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNDI2Njc5LCJpYXQiOjE3NTA0MjYzNzksImp0aSI6ImU0OWFlYWY5OTBmNjRhMWFhMmZkZmRjZTc4OWNmN2NiIiwidXNlcl9pZCI6Mn0.vJtWHkF5dgsGOOXFPYpZ5HmZNmQCZWkn7xPmyunt1nI

{
    "name": "Test Authorized Product",
    "description": "This is a test product.",
    "price": 100.00,
    "stock": 10
}

###
# Post /api/v1/token to get a token
POST http://127.0.0.1:8000/api/v1/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
# POST /api/v1/token/refresh to refresh the token
POST http://127.0.0.1:8000/api/v1/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MDUxMzMwNSwiaWF0IjoxNzUwNDI2OTA1LCJqdGkiOiJlOWE2Yjg5ZjNhNmI0MjMzOTFlMTA4OTU4NTExYmQzNSIsInVzZXJfaWQiOjJ9.ejCTz9Nr95-2mqNU65eebM2m6gbs5IE8x_NRjtcXs-Q"
}

###
# Get /api/v1/products/8/ to retrieve a specific product

GET http://127.0.0.1:8000/api/v1/products/8/ HTTP/1.1

###
# DELETE /api/v1/products/8/ 

DELETE http://127.0.0.1:8000/api/v1/products/8/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNDI4NTIyLCJpYXQiOjE3NTA0MjgyMjIsImp0aSI6ImUyMWQyMDAzNjQxMTQzOGM4ZDg1OGU2ZWU0NmU1YTllIiwidXNlcl9pZCI6Mn0.vJ5XZJRS2cjkEwi-mvIMeojVCAzi34i93IvBRPrzM0s

###
# PUT /api/v1/products/8/ to update a specific product

PUT http://127.0.0.1:8000/api/v1/products/8/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNDI4NjM4LCJpYXQiOjE3NTA0MjgzMzgsImp0aSI6IjQ3MDI1OTQwODBlYTRiZmNiZWMwNTI4MzA1YzQ5Nzc2IiwidXNlcl9pZCI6M30.QA3AygB_vQWKBuB_T-zguZ-e-7MGcl1gvW6QgYoFnN8

{
    "name": "Updated Product Name",
    "description": "Updated product description.",
    "price": "150.00",
    "stock": 5
}