#  API Testing for Product Management

# GET /api/v1/products/

GET http://127.0.0.1:8000/api/v1/products/ HTTP/1.1

###
# POST /api/v1/products/

POST http://127.0.0.1:8000/api/v1/products/ HTTP/1.1
Content-Type: application/json

{
    "name": "Test Product",
    "description": "This is a test product.",
    "price": 100.00,
    "stock": 10
}